mipengine/mip2

- packages/mip/src/util/dom/rect.js
fix #17 
修复在**根页面**中使用 `viewport.get/setScrollTop()` 的问题。
> fix: get/setScrollTop in viewport

- packages/mip/examples/page/iframe/input-iframed.html
- packages/mip/examples/page/index.html
- packages/mip/src/page/const/index.js
- packages/mip/src/page/index.js
- packages/mip/src/page/util/dom.js
- packages/mip/src/viewer.js
- packages/mip/src/viewport.js
修复以下几个问题：
1. #29，原因是刷新之后，点击头部返回按钮（不是浏览器的返回按钮）时，没有隐藏掉原始页面中的内容。
2. 手百 iOS 9, 10 存在滑动之后白屏的现象，禁用掉弹性滚动特性。
3. 部分机型存在关闭软键盘后，iframe 高度没有恢复的问题。目前尝试的一种解决方案是监听 input 的 blur  事件，重新设置所有 iframe 的高度。
> Fix resize

- packages/mip/src/page/router/history.js
Fix #36 
原本为了修复 安卓 QQ 浏览器特有的一个问题：必须先 `pushState`，再创建 iframe，否则此时后退不触发 `popstate`。因此我们修改了 router 中这两个操作的顺序。
但是影响到了 iOS QQ 浏览器，因此加上了精确的 UA 检测。
> fix: iOS QQ browser

- packages/mip/.npmrc
chromedriver 这个依赖要下载driver文件，直接 npm install 会失败，配置国内镜像地址，能快速下载
> 增加 chromedriver 镜像地址，解决使用 npm 安装失败的问题

- packages/mip/src/page/index.js
**相关 ISSUE:** https://github.com/mipengine/mip2/issues/116
**1、升级点** `scrollToHash` 中 `document.querySelector` 替换为 `document.getElementById`
**2、影响范围** 所有滚动到 hash 的操作
**3、自测 Checklist** 官网上测过相关升级点
**5、自测机型和浏览器**
> Fix invalid hash selector

- .travis.yml
- README.md
travis 运行单测时， node7 环境下安装依赖经常出错，影响构建状态。mip 本身和 node 版本无关，所以留一个就行了。
> remove node 7

- packages/mip/examples/page/index.html
- packages/mip/src/page/index.js
- packages/mip/test/e2e/cases/scroll-to-anchor.html
- packages/mip/test/e2e/specs/scroll-to-anchor.js
**相关 ISSUE:**  #125
修复 #125 描述的 Bug，
点击页面中锚点，滚动到相应位置，
此时刷新页面后仍然能正确滚动到之前的锚点位置。
目前线上除了 MIP 官网，没有其他产品线使用这个功能。
提交中包含了 e2e 测试用例。
1. 打开 scroll-to-anchor.html
2. 点击 `<a id="anchor">` 滚动到锚点处
3. 在当前页面刷新，滚动到锚点处
4. 打开 index.html 通过 mip-link 跳转到 scroll-to-anchor.html 验证 iframe 下的情况
5. 点击 iframe 中的 `<a id="anchor">` 滚动到锚点处
**5、自测机型和浏览器**
> 修复 #125 刷新后滚动到锚点

- packages/mip/examples/builtin-components/mip-img.html
- packages/mip/src/components/mip-carousel.js
- packages/mip/src/components/mip-img.js
- packages/mip/test/specs/components/mip-carousel.spec.js
#89 
- 修复轮播图mip-img嵌套问题，即mip-img被嵌套在其他元素下再被添加到mip-carousel中
- 增加mip-img长图浏览效果，在examples/mip-img下可以看到长图浏览效果
不会影响旧功能
**5、自测机型和浏览器**
> [提测] 修复轮播图mip-img嵌套问题，增加mip-img长图浏览效果

- packages/mip/examples/page/data.html
- packages/mip/src/components/mip-bind/mip-data.js
- packages/mip/test/specs/components/mip-bind.spec.js
#181 
修复 bug：
mip-data 为异步数据提供了一个 window.mipDataPromises 的 promise 数组，用于检测是否异步设置数据成功
但目前 then 的触发发生在获取数据，而非设置数据
此次提交调整了该数组暴露的 promise，当数据加载成功时，需要真正获取到其中的 json 数据并设置成功后才会 resolve
使用 <mip-data src=""> 标签异步获取数据
（暂时没发现线上 case，此 case 是一位同学迁移页面时发现，对方还未上线）
已新增 testcase 并跑过
- [] 是否覆盖了 sf 打开 MIP 页
- [] 是否验证了极速服务 MIP 页面效果
**5、自测机型和浏览器**
> 【免测】调整 mipDataPromises 的 resolve 时机

- packages/mip/src/vue-custom-element/index.js
**相关 ISSUE:** https://github.com/mipengine/mip2/issues/184
**1、升级点** 去除当 vue 组件缺少 template 和 render 时提供的默认 render 函数
**2、影响范围** 基本无影响
**5、自测机型和浏览器**
> Do not override render in Vue.customElement

- packages/mip/src/components/mip-shell/index.js
- packages/mip/src/viewer.js
#187 
切换页面时，允许直接读取目标页面的配置并更新头部标题
不影响线上的 case。需要子类增加配置才会生效。
和 @Espoir-L 在 BOS 环境上进行调试成功
**5、自测机型和浏览器**
> 增加配置项，允许直接读取目标页面的配置以决定标题

- packages/mip/src/components/mip-shell/index.js
临时修复预览机上的“登录”页面标题不对的问题
临时修复预览机上的“登录”页面标题不对的问题
蓝犀牛跳转到登录页面时的标题
使用本地代理测试无误
**5、自测机型和浏览器**
> 临时修复登录标题不对的问题

- packages/mip/src/index.js
#221 
现有性能日志是等所有字段收集完成后才一起发送消息至外层，可能造成了部分日志丢失。
去掉此处的判断，每次有字段更新就发送，由外层进行日志收集。
不影响功能，可能会影响性能日志量
SF 下日志发送成功，字段正确。
**5、自测机型和浏览器**
> 【免测】修复性能日志可能存在丢失情况

- packages/mip-cli/README.md
- packages/mip-cli/bin/mip2
- packages/mip-cli/bin/mip2-add
- packages/mip-cli/bin/mip2-addPlugin
- packages/mip-cli/bin/mip2-build
- packages/mip-cli/bin/mip2-dev
- packages/mip-cli/bin/mip2-init
- packages/mip-cli/bin/mip2-sw
- packages/mip-cli/bin/mip2-validate
- packages/mip-cli/lib/utils/compat.js
- packages/mip-cli/package.json
1. mip-cli 在低于 nodejs 7.6 以下的版本会自动调用 babel-register 做兼容处理
1. mip-cli
> 增加 mip-cli 对低版本 nodejs 兼容支持

- packages/mip/examples/page/class-style-binding.html
- packages/mip/src/components/mip-bind/compile.js
- packages/mip/src/components/mip-bind/util.js
- packages/mip/test/specs/components/mip-bind.spec.js
#225 
- 单变量情况下，支持多个 class 的直接绑定
- 同时修复了一个如果 m-bind 绑定的数据再 mip-data 被延迟注册，将无法解析数据的问题
- 同时修复了 m-bind 绑定变量时叠加字符串解析失败的问题
影响 issue 中提到的一个变量绑定了多个 class 的情况
已通过自测 case + 单测覆盖
**5、自测机型和浏览器**
> 【申请免测】修复 m-bind class 绑定问题

- packages/mip/src/index.js
#230 
增加 `window.MIP` 和 `window.MIP.version` 的判断，如果两者有一个为 `undefined`，则表示之前没有加载过 mip.js，走正常逻辑；否则表示之前加载过（或者预取状态），不执行初始化逻辑，相当于没有执行。
不影响线上页面展示（因为线上不存在重复引用）
待预取上线之后，在预取状态下不应该打印 mip-shell 的相关警告
* 在 mip.js 的引用之前添加 `<script>window.MIP = {version: 'preload'}</script>`，页面不执行初始化
* 重复2次 mip.js 的引用，页面效果正常
* 页面不作任何改动，效果正常
**5、自测机型和浏览器**
> 支持 prefetch，避免重复请求

- packages/mip/src/styles/mip-base.less
- packages/mip/src/viewer.js
**相关 ISSUE:**
#216 
iframe 不会被动态添加的内容撑开宽度。
iOS 下出现广告的场景。
**5、自测机型和浏览器**
> fix: iframe 宽度撑开

- packages/mip/examples/page/class-style-binding.html
- packages/mip/examples/page/test.html
- packages/mip/src/components/mip-bind/util.js
- packages/mip/test/specs/components/mip-bind.spec.js
#225 
上次 pr 直接根据问题描述修复了基础变量绑定的多个class的问题，没有发现 issue 中还有其他写法的叠加场景
如 issue 中的写法, 数组写法绑定 class，其中数组内的变量绑定多个 class 的值，预期应该解析成功
数组写法中，某个数组内 item 的变量绑定多个 class 的值
单测+case 自测
**5、自测机型和浏览器**
> 修复class绑定数组写法中变量指向内容为多个class的问题

- packages/mip/postcss.config.js
#231 
1. 增加 postcss 的 autoprefixer 的配置，扩大 autoprefixer 的兼容范围
1. 增加华为默认浏览器等低端浏览器对 flex 属性的兼容
> 增加 autoprefixer 的配置扩大浏览器兼容范围

- packages/mip/src/styles/mip-base.less
https://github.com/mipengine/mip2-extensions/issues/254
对 `<html>` 应用 `overflow-x:hidden` 会导致在页面高度不足的情况下（组件预览页面）无法显示菜单下拉内容。
MIP 下拉菜单组件的[预览页面](https://www.mipengine.org/examples/mip-extensions/mip-nav-slidedown.html)
**5、自测机型和浏览器**
> fix: remove 'overflow-x:hidden' from html

- packages/mip/src/page/index.js
**相关 ISSUE:** https://github.com/mipengine/mip2/issues/248
**1、升级点**  支持滚动至 `<a name="">` 的锚点
**2、影响范围** 线上功能无影响
已于本地自测，主要用于官网文档，如
https://www.mipengine.org/v2/guide/mip-standard/mip-components-spec.html#4
**5、自测机型和浏览器**
> 【免测】修复滚动至 <a name=""> 锚点的行为

- packages/mip/src/viewer.js
#266 
使用 `viewer.open` 时如果目标链接是非 MIP 页面也可以使 `replace` 参数生效
线上暂无这样的使用方式
和 @zhuguoxi 在 BOS 上测试过新的用法，一切正常
**5、自测机型和浏览器**
> 【免测】非 MIP 链接也支持 replace

- .travis.yml
- packages/mip-cli/lib/addPlugin.js
- packages/mip-cli/lib/check-version.js
- packages/mip-cli/lib/server/index.js
- packages/mip-cli/lib/utils/plugin.js
**相关 ISSUE:**  https://github.com/mipengine/mip2/issues/257
- mip2 cli plugin 兼容入口文件 index.js 被移除的情况
- mip2 cli plugin 模块查找失败时输出错误信息详情
- mip2 cli 版本提示格式调整
- mip2 travis 构建增加 retry 机制
此次改动只涉及 mip2 cli ，对线上 mip 核心无影响
> 【免测】mip2 cli plugin 容错及输出信息格式修复

- packages/mip-sandbox/lib/sandbox.js
- packages/mip-sandbox/package-lock.json
- packages/mip-sandbox/package.json
- packages/mip-sandbox/test/spec/sandbox.spec.js
#270 
1. 修复 mip-sandbox 旧接口引用路径错误的 bug
2. 增加 test case 覆盖旧接口
1. 修复安装了 mip-sandbox@1.0.23 的 mip 核心编译产物报错的 bug
> 【免测】修复 mip-sandbox@1.0.23 旧接口引用路径错误的 bug

- packages/mip/examples/page/components/mip-shell-novel.js
- packages/mip/src/components/mip-shell/index.js
- packages/mip/src/page/util/feature-detect.js
#280 
提供给继承 SHELL 的子类一种异步渲染的方式，提升首屏性能
绑定事件成为了异步，需验证SHELL的按钮可以正常点击即可
右上角的更多按钮可以点击，左上角后退按钮可以点击
**5、自测机型和浏览器**
> 首屏渲染增加异步方式

- packages/mip/src/components/mip-img.js
- packages/mip/src/register-element.js
#276 
图片提前一屏加载
图片加载
chrome 模拟器 小说
IOS11.4  uc浏览器  手百
**5、自测机型和浏览器**
> 🐛 添加mip2的图片提前一屏渲染

- packages/mip/src/components/mip-shell/index.js
- packages/mip/src/page/util/feature-detect.js
#280 
把 shell 中一些后续操作（例如绑定事件，创建首屏不需要的图层等）移动为异步操作，这样不影响和 SF 的通讯
并没有添加新功能，只需保证和线上效果一致即可。
因为蓝犀牛（极速服务）和小说各自拥有自己的子类 shell，且模式不同（极速服务含有异步更新机制），因此对这两者的 shell 头部的三个按钮（后退，更多，关闭）需要重点测试
另外PC模拟的安卓系统打开小说能够正常展现页面（之前使用 idleCallback 碰上过白屏的情况）
蓝犀牛打开页面后更多和关闭可以点击，切换到地址页面可以正常后退到蓝犀牛首页
小说页面能够正常打开，能够切换页面，之后能够正常后退到搜索页。
小说的shell可以切换黑夜模式。
**5、自测机型和浏览器**
> 将shell的一些后续操作移动到异步中，不卡住和SF的通讯

- packages/mip/examples/performance/analyze.js
- packages/mip/src/components/mip-shell/index.js
- packages/mip/src/components/mip-video.js
- packages/mip/src/index.js
- packages/mip/src/page/const/index.js
- packages/mip/src/page/router/index.js
- packages/mip/src/viewer.js
- packages/mip/test/specs/page/router.spec.js
#215 
如 ISSUE 整理，MIP 和 SF 的通信的消息名称有各种形式（连写，驼峰，下划线等等）
为了后期的开放，需要进行统一。
原则上和线上效果保持一致即可。
主要在于切换页面时的几个消息，SF目前改成新旧两种格式都接受。
使用线上环境代理本地脚本进行过自测。
蓝犀牛能够正常打开，能够进入地址选择页，能够后退，能够前进（浏览器上的），能够关闭页面
小说能够正常打开，能够切换到下一页，能够后退（浏览器上和 shell 上的）
**5、自测机型和浏览器**
> MIP 和 SF 消息格式统一

- packages/mip/src/components/mip-img.js
- packages/mip/src/viewer.js
- packages/mip/test/specs/components/mip-img.spec.js
#304 
mip-img 在大图浏览的效果改为 `backgroud-size: contain` ，即高为 100%或 宽100%，二者必然满足一项。
有使用 mip-img 的 popup 属性的页面
可直接看例子的效果 http://localhost:8080/examples/builtin-components/mip-img.html
**5、自测机型和浏览器**
> 修改 mip-img 的大图浏览效果，and lint view.js

- packages/mip/build/config.js
- packages/mip/src/index.js
- packages/mip/test/specs/index.spec.js
- packages/mip/test/specs/resources.spec.js
#312
去除 export MIP，避免在 waitDocumentReady 之前 MIP 直接挂载到window下
影响 js 提到head 使用 async 属性
**5、自测机型和浏览器**
> 去除 index.js export mip

- packages/mip/src/client-prerender.js
- packages/mip/src/page/util/dom.js
- packages/mip/src/util/fn.js
- packages/mip/src/viewer.js
- packages/mip/test/specs/util.spec.js
- packages/mip/test/specs/util/fn.spec.js
#328 
每一条和 SF 的通讯信息都设置 name，格式如 `iframe-shell-xxxx`
对代码正常运行没有影响，但能修复 328 提到的问题，让 SF 能够区分正常页面和预渲染页面（需配合 SF 的修改一起）
联合 @oott123 进行过线下测试，效果正常
**5、自测机型和浏览器**
> 每一条给 SF 的消息都带上name

- packages/mip-cli/CHANGELOG.md
- packages/mip-cli/package-lock.json
- packages/mip-cli/package.json
- packages/mip-component-validator/package-lock.json
- packages/mip-component-validator/package.json
- packages/mip-sandbox/README.md
- packages/mip-sandbox/lib/keywords.js
- packages/mip-sandbox/package-lock.json
- packages/mip-sandbox/package.json
#347 
1. 新增 mip-sandbox 白名单 atob TextEncoder TextDecoder，并发布新版本
2. 升级 mip-component-validator 的 mip-sandbox 版本依赖，并发布新版本
3. 升级 mip-cli 的 mip-component-validator 和 mip-sandbox 的版本依赖，并发布新版本
1. 仅影响第三方站长组件开发时的 mip-sandbox 白名单校验
无
> 【免测】增加 mip-sandbox 白名单

- packages/mip/src/components/mip-shell/index.js
- packages/mip/src/viewer.js
#280 
还是把一些无需立刻执行的操作异步进行，避免阻塞发送消息
首屏shell（例如头部）的渲染以及所有 a 链接的事件绑定现在都变成了异步
另外小说广告之前有依赖顺序的问题，需要确认修改后是否还有这个问题（当时就是因为这个而回滚的）
采用线下代理的方式测试过极速服务&小说，基本功能正常
**5、自测机型和浏览器**
> 再次尝试异步操作提升性能

- packages/mip/examples/page/index.html
- packages/mip/src/index.js
- packages/mip/src/styles/mip-page.less
#344 
在 SF 情况下，MIP 首个页面不展现自己的 Loading
在 MIP1 的页面尤其有效，MIP2因为 SF 的 Loading 是全覆盖页面的样式，所以看不出差别。
[https://m.baidu.com/mip/c/s/m.meishichina.com/recipe/176377/](https://m.baidu.com/mip/c/s/m.meishichina.com/recipe/176377/)
主要影响 MIP1 的页面直接迁移成 MIP2 的 JS 之后，两层 Loading 问题的修复
使用代理线上JS和CSS的方式测试过上面的红烧肉页面，没有两层 Loading
另外回归过极速服务搬家，小说阅读器，翻页等 Loading 正常展现。
单独打开 MIP 页面（不在SF里）也正常展现 Loading
**5、自测机型和浏览器**
> SF情况下首屏不展现 loading

- packages/mip/src/services/extensions.js
- packages/mip/src/services/services.js
- packages/mip/test/specs/services/services.spec.js
**相关 ISSUE:** 
**1、升级点**
- mip2-extensions 中的 service 为外部 service，注册时应直接实例化
- 线上无任何影响，因为根本没有外部 service
- 不影响原注册流程
**5、自测机型和浏览器**
> 【免测】注册外部 service 时直接实例化

- packages/mip/src/styles/mip-base.less
#182 
删除基础样式中的 100px，请使用mip-rem
有用到基础样式中的 100px 和 rem 的站点
**5、自测机型和浏览器**
> 【WIP】删除基础样式中的 100px

- packages/mip/examples/page/index.html
- packages/mip/src/components/mip-shell/dom.js
- packages/mip/src/components/mip-shell/index.js
- packages/mip/src/components/mip-shell/util.js
- packages/mip/src/page/index.js
- packages/mip/src/page/util/dom.js
- packages/mip/src/styles/mip-shell.less
本次改动主要针对相似度大但不能压缩的代码（例如报错信息的字符串，SVG内容等），对功能上没有任何改变，目的还是为了缩小 mip.js 的体积
> 精简一些重复且不能压缩的代码

- packages/mip/src/runtime.js
**1、升级点** 
- 修复预取使 preregisterExtensions 可能为对象的问题
**2、影响范围** 
**5、自测机型和浏览器**
> 修复预取使 preregisterExtensions 可能为对象的问题

- packages/mip-cli/CHANGELOG.md
- packages/mip-cli/lib/dev.js
- packages/mip-cli/lib/server/index.js
- packages/mip-cli/lib/server/middleware/directory/dir-template.etpl
- packages/mip-cli/lib/server/middleware/directory/index.js
- packages/mip-cli/package.json
#350 
#351 
dev server 增加目录浏览功能
禁止直接通过url访问example和mock目录外的静态资源
影响在mip-cli dev模式下调试代码
**5、自测机型和浏览器**
> mip-cli dev模式添加目录浏览功能并对静态资源访问作限制

- packages/mip/package-lock.json
- packages/mip/package.json
- packages/mip/src/components/mip-iframe.js
- packages/mip/src/components/mip-img.js
- packages/mip/src/components/mip-shell/switchPage.js
- packages/mip/src/index.js
- packages/mip/src/page/util/dom.js
- packages/mip/src/page/util/ease-scroll.js
- packages/mip/src/page/util/feature-detect.js
- packages/mip/src/register-element.js
- packages/mip/src/resources.js
- packages/mip/src/runtime.js
- packages/mip/src/services/extensions.js
- packages/mip/src/util/custom-event.js
- packages/mip/src/util/fn.js
- packages/mip/src/viewer.js
- packages/mip/src/viewport.js
- packages/mip/test/specs/components/mip-carousel.spec.js
- packages/mip/test/specs/components/mip-iframe.spec.js
- packages/mip/test/specs/components/mip-img.spec.js
- packages/mip/test/specs/components/mip-layout.spec.js
- packages/mip/test/specs/components/mip-pix.spec.js
- packages/mip/test/specs/components/mip-rem.spec.js
- packages/mip/test/specs/components/mip-video.spec.js
- packages/mip/test/specs/page/util.spec.js
- packages/mip/test/specs/register-element.spec.js
- packages/mip/test/specs/resources.spec.js
- packages/mip/test/specs/services/extensions.spec.js
- packages/mip/test/specs/viewport.spec.js
- packages/mip/test/specs/vue-custom-element/index.spec.js
#380 
#314 补充：#380 是 #314 的子集，#380 已经关闭，后续请关注 #314 
- 组件异步执行 `build` 改回同步执行（之前因为优化的原因改成异步，虽然确实有10%左右的性能提升，但是也造成一些无法解决的问题，比如 mip-baidu-stats 无法发送自定义统计的问题，又比如无法在build回调里监听 onload domcontentloaded 事件等问题）
- 组件 `MIP.push` 由 `whenBodyAvailable` 的 promise 改为同步执行，原因与上一条相同
- 将 `resources.update` 由原来的 promise 延迟执行改为用 `requestAnimationFrame` 实现延迟执行，将大大减少首屏 update 次数，从而减少 reflow 的问题，提高性能
-  document-register-element 版本改成了1.13.1， 更新到最新版
- 把 `handleBrowserQuirks` 里的兼容性且严重造成 reflow 的代码放到 `setTimeout` 里执行，避免阻塞 `postMessage` 的消息发送
**5、自测机型和浏览器**
> Remove build asynchronous and performance optimization

- packages/mip/src/components/mip-shell/index.js
#426 
在直接打开MIP页面的情况下允许浏览器记录滚动位置
所有直接打开MIP页面时。
在搜索结果页用 SF 打开的不受影响。
采用代理方式直接打开线上小说页面（mipcdn地址的），滚动到下方之后刷新，能恢复到刚才滚动的位置
**5、自测机型和浏览器**
> 在直接打开MIP的情况下记录滚动位置

- packages/mip/src/client-prerender.js
- packages/mip/src/log/firstscreen-label.js
- packages/mip/src/page/const/index.js
- packages/mip/src/performance.js
- packages/mip/src/resources.js
- packages/mip/test/specs/client-prerender.spec.js
- packages/mip/test/specs/log/error-monitor.spec.js
- packages/mip/test/specs/log/firstsceen-label.spec.js
**1、升级点** 
1. 预渲染对标记为 `firstscreen=1` 首屏元素（主要是图片）进行提前渲染
2. 修正在预渲染下因 iframe 隐藏无法识别元素是否在首屏，造成的 otm 指标统计不准确
3. 发送首屏标记准确度日志给外层用于分析
**2、影响范围** 
1. 一定程度上影响预渲染下的 otm 指标
2. 有首屏标记图片的预渲染过程
1. 预渲染功能正常
2. otm 指标符合预期
3. 首屏准确度日志反馈正常
**5、自测机型和浏览器**
> feat: first screen label

- packages/mip/src/components/mip-fixed.js
#90 
- mip-fixed 作用范围通过 still 属性进一步收敛，避免对 mip1 现有组件和站点污染
mip-fixed 组件（mip1 的站点和 mip2 的站点）
**5、自测机型和浏览器**
> 【免测】兼容 mip1 存量站点和组件中关于 mip-fixed 组件在 iOS + iframe 情况下挪出 body

- packages/mip/src/components/mip-shell/index.js
#437 
修复 MIP1 升级页面切换页面时标题不变化的问题
自动生成 `<mip-shell>` 标签时，会读取目标 `<title>` 的值作为标题。
已有 `<mip-shell>` 或者子类标签时不影响（如小说）
使用代理的方式
测试问题站点 [http://m.9978.tv](http://m.9978.tv)，切换页面后标题可以变化
测试小说页面，和线上效果一致
**5、自测机型和浏览器**
> 修复 MIP1 升级页面切换页面时标题不变化的问题

- packages/mip/src/components/mip-carousel.js
- packages/mip/src/components/mip-shell/switchPage.js
- packages/mip/src/styles/mip-base.less
- packages/mip/test/specs/components/mip-carousel.spec.js
#436
由于mip1有组件使用到 hide class，导致了元素被强制隐藏的bug，因此修改hide为mip-hide，添加mip前缀，这样就不容易产生冲突与误用
所有使用到 hide class的组件，目前已知包括核心的mip-carousel和mip-shell、mip1第三方组件mip-header-qiehuan，修改后显示正常
相关mip2站点
**5、自测机型和浏览器**
> change hide to mip-hide

- packages/mip/src/components/mip-fixed.js
**问题：**
MIP1站点重写 mip-layout-container 导致 MIP2 替换 MIP1 后无法隐藏 loading，
> 之前针对 mip-fixed display none 改为 mip-fixed display: none!important 在 ios9以下手机有兼容性问题，无法解决
站点 http://mip.cntrades.com/15995352952/sell/itemid-170607633.html
**方案：**
针对 mip-fixed 先把 mip-layout-container 去掉，这个不会对现有样式造成影响
**5、自测机型和浏览器**
> fix: hide loading in mip1 site

- packages/mip/examples/builtin-components/mip-video.html
- packages/mip/src/components/mip-video.js
- packages/mip/src/viewer.js
- packages/mip/test/specs/components/mip-video.spec.js
**相关 ISSUE:** https://github.com/mipengine/mip2/issues/448
**1、升级点** 
1. 视频播放时，通过链接打开新的 MIP 页面时（iframe），暂停视频播放
2. 当通过 cache-first 链接跳回原页面时，重置视频状态到开头
- 所有使用 mip-video 的站点
1. 暂停视频播放
- video 页面 (rootPage) -> 其他页面 (iframe) -> video 页面 (iframe)
- video 页面 (iframe) -> 其他页面 (iframe) -> video 页面 (iframe)
2. 重置视频状态
- video 页面 (iframe) -> 其他页面 (iframe) --(cache-first)-> video 页面 (iframe)
- video 页面 (iframe) -> 其他页面 (iframe) --后退-> video 页面 (iframe)
**5、自测机型和浏览器**
> fix: Controls video when page is switching

- packages/mip/src/fixed-element.js
#442 
保持与mip1逻辑一致，在sf环境下隐藏position: fixed元素，而在原始页中可以显示position: fixed元素
使用了position: fixed的站点，原来在独立站被隐藏的position: fixed元素现在可以显示了
**5、自测机型和浏览器**
> 【免测】在sf环境下隐藏position: fixed元素

- packages/mip/src/components/mip-bind/bind.js
**相关 ISSUE:** https://github.com/mipengine/mip2/issues/413
**1、升级点** 
- 将 `mip-bind` 的 `Set` 换成了 `{}`
**2、影响范围** 
- 含有 `m-bind` 和 `mip-data` 的页面
**5、自测机型和浏览器**
> 【免测】移除 mip-bind 依赖的 Set 特性

- packages/mip/deps/mip-components-webpack-helpers.js
#491 
1. 修改 helper 的 vue-style-loader/lib/addStylesClient 的插入 css 的逻辑，由 appendChild 变成 insertBefore
2. 删掉 ssr 相关逻辑
3. 删掉 IE8 IE9 的兼容逻辑
1. MIP2 组件的样式权重
1. 组件 css 正确插入 head 顶部
**5、自测机型和浏览器**
> 更新 helper 修改 css 插入 head 的逻辑

- packages/mip/deps/mip-components-webpack-helpers.js
#491 
1. 组件 css 插入位置从 insertBefore(style, head.firstChild) 改成 insertBefore(style, cssLinkNext || head.firstChild)
1. mip-shell-xiaoshuo 等会覆盖 mip.css 样式的组件
1. 线上小说样式正常
**5、自测机型和浏览器**
> 修改 helper 插入组件 css 的位置

- packages/mip-component-validator/src/rules/lib/whitelist.txt
- packages/mip-sandbox/lib/global-detect.js
- packages/mip-sandbox/lib/global-mark.js
- packages/mip-sandbox/lib/keywords-generate.js
- packages/mip-sandbox/package-lock.json
- packages/mip-sandbox/package.json
- packages/mip/package-lock.json
- packages/mip/package.json
#464 
#470 
1. 增加 MIP.sandbox.document.execCommand 方法
2. MIP.sandbox.document.createElement('script') 时打 console.error('[MIP] 禁止创建 SCRIPT 标签引入第三方 JS 脚本')
3. 同步线上 NPM 白名单
1. 第三方站长组件在使用 document.createElement('script') 时控制台输出警告信息，但不影响功能；
2. 其余的无
1. 控制台输入 MIP.sandbox.document.execCommand('copy') 返回 true，说明新增方法正常工作；
2. 控制台输入 MIP.sandbox.document.createElement('script') 控制台输出警告信息，并且方法返回 `<script>` ，输入参数改为 "SCRIPT" "ScripT" 均正常工作。说明输出警告逻辑正常；
3. 控制台输入 MIP.sandbox.document.createElement('div') 返回 `<div>` 同时没有任何警告输出，说明原有 document.createElement 方法不受影响；
**5、自测机型和浏览器**
> MIP 核心升级 mip-sandbox

- packages/mip/src/components/index.js
- packages/mip/src/page/util/dom.js
- packages/mip/src/viewer.js
**1、升级点** 
- 允许独立站通过 `<mip-shell disabled></mip-shell>` 禁用 `mip-shell`
- 无影响
- https://mip.64365.com 禁用功能生效
- 搜索结果页无影响
**5、自测机型和浏览器**
> feat: 允许独立站禁用 mip-shell

- packages/mip-cli/CHANGELOG.md
- packages/mip-cli/bin/mip2-build
- packages/mip-cli/package-lock.json
- packages/mip-cli/package.json
在 mip-cli build 出错时，中断 node 进程，编译脚本能捕获错误
mip-cli 编译异常的情况
**5、自测机型和浏览器**
> [免测]build 异常处理，便于编译脚本捕获异常

- packages/mip/src/runtime.js
- packages/mip/src/viewer.js
**1、升级点** 
- 确保 pageMeta 为合法对象
- 禁用 shell 后不代理链接点击事件（但仍需保留通过 viewer.open 打开新页面时的判断）
**2、影响范围** 
- 出问题的独立站
- 官网
- 元尊
**5、自测机型和浏览器**
> fix: 修复核心全量后已知 bugs

- packages/mip-cli/CHANGELOG.md
- packages/mip-cli/package-lock.json
- packages/mip-cli/package.json
- packages/mip-sandbox/lib/keywords-generate.js
- packages/mip-sandbox/package-lock.json
- packages/mip-sandbox/package.json
- packages/mip-sandbox/test/spec/generate.spec.js
#563 
1. mip-cli 升级 mip-sandbox 版本依赖，增加 swan 白名单
仅影响组件开发
**5、自测机型和浏览器**
> 【免测】mip-cli 增加 swan 白名单

- packages/mip/src/experiment/config.js
- packages/mip/src/experiment/index.js
- packages/mip/src/index.js
- packages/mip/test/specs/experiment/index.spec.js
#559 
新增前端小流量机制
暂时不会对线上造成影响
**5、自测机型和浏览器**
> 新增 mip 前端小流量机制

- packages/mip/src/components/mip-img.js
#573 
- 去除 mip-img 中用 js 修改 img src 指向 mip cache url 的逻辑
- mip-img 组件
**5、自测机型和浏览器**
> 【免测】修复 mip-custom 动态引入的组件中包含 mip-img 会导致图片的 src 被错误修改成 mip cache url 的问题

- packages/mip-cli/CHANGELOG.md
- packages/mip-cli/package-lock.json
- packages/mip-cli/package.json
- packages/mip-sandbox/lib/keywords-generate.js
- packages/mip-sandbox/lib/unsafe-replace.js
- packages/mip-sandbox/package-lock.json
- packages/mip-sandbox/package.json
- packages/mip-sandbox/test/spec/generate.spec.js
- packages/mip-sandbox/test/spec/sandbox.spec.js
- packages/mip/package-lock.json
- packages/mip/package.json
#576 
#554 
1. window.MIP.sandbox 增加 BMap\BMapLib 支持百度地图 API 的加载
1. mip-map 地图组件以及依赖 mip-map 的第三方站长组件
1. 蓝犀牛正常工作
**5、自测机型和浏览器**
> mip.js 沙盒对象增加 BMap\BMapLib

- packages/mip/build/config.js
- packages/mip/src/base-element.js
- packages/mip/src/custom-element.js
- packages/mip/src/mip1-polyfill/element.js
- packages/mip/src/services/extensions.js
- packages/mip/src/services/vue-compat.js
- packages/mip/src/util/string.js
- packages/mip/src/vue-custom-element/index.js
- packages/mip/test/specs/base-element.spec.js
- packages/mip/test/specs/services/extensions.spec.js
- packages/mip/test/specs/services/vue-compat.spec.js
- packages/mip/test/specs/util/string.spec.js
- packages/mip/test/specs/vue-custom-element/index.spec.js
**相关 ISSUE:** https://github.com/mipengine/mip2/issues/584
**1、升级点** 
- 在被监听的属性变更时，自动调用 `handle${propName}Change` 回调
**2、影响范围** 
- 新功能，无影响
**5、自测机型和浏览器**
> feat: Call the corresponding handlers when attributes changed

- packages/mip/src/components/mip-img.js
- packages/mip/test/specs/components/mip-img.spec.js
#582 
#517 
- 查看图片支持缩放
- 图片长按可以下载
在手百点击非跳转的图片，会通过手百浏览器打开，图片可缩放与下载
**5、自测机型和浏览器**
> mip-img 支持调起手百图片浏览器

- packages/mip/src/components/mip-img.js
- packages/mip/test/specs/components/mip-img.spec.js
在手百中，popup 属性的图片点击调起大图，iframe 下所有图片长按调起大图
**5、自测机型和浏览器**
> 修改 mip-img 手百调起逻辑

- packages/mip/src/components/mip-shell/index.js
- packages/mip/src/styles/mip-shell.less
**相关 ISSUE:** 
**1、升级点**
- 页面没有 mip.css 时，页面出现大箭头，现在去掉了
**2、影响范围** 
- 无
**5、自测机型和浏览器**
> fix: Fix mip-shell display

- packages/mip-cli/CHANGELOG.md
- packages/mip-cli/lib/builder/webpack/config/index.js
- packages/mip-cli/package-lock.json
- packages/mip-cli/package.json
#606 
1. 将 core-js 的路径到 CLI 的依赖里去找
1. 后续上线组件和线下的组件开发
1. mip2-extensions 调试正常，编译正常
2. mip2-extensions-platform 编译正常
**5、自测机型和浏览器**
> 修复 CLI 编译 BUG

- packages/mip/src/util/event-action.js
#608 
- 在 on 事件的 setData 函数中，可以通过 event 获取事件暴露的数据
无
**5、自测机型和浏览器**
> 【免测】bugfix: 修复事件 event 数据丢失问题

- packages/mip/src/components/mip-carousel.js
- packages/mip/src/components/mip-img.js
- packages/mip/src/styles/mip-img.less
- packages/mip/test/specs/components/mip-carousel.spec.js
- packages/mip/test/specs/components/mip-img.spec.js
根据手百站点检测要求，自动轮播也能够打开大图，popup 时暂停轮播，关闭 popup 后继续轮播
使用 mip-carousel 的站点
**5、自测机型和浏览器**
> fix: 自动轮播支持 popup

- packages/mip/src/fixed-element.js
#616  
- 修复 mip-fixed 因为在搜索落地页环境额外定义了 position: fixed 被隐藏的问题
- 搜索落地页下的 mip cahce  页面中的 mip-fixed 组件
**5、自测机型和浏览器**
> 【免测】修复 mip-fixed 因为在搜索落地页环境额外定义了 position: fixed 被隐藏的问题

- packages/mip/examples/mip2/mip-test-slot.html
- packages/mip/examples/mip2/mip-test-slot.js
- packages/mip/src/vue/core/instance/render-helpers/render-slot.js
- packages/mip/src/vue/core/instance/render.js
- packages/mip/src/vue/core/vdom/patch.js
#613 
修复 v-for 配合 slot 使用导致的渲染 slot 缺失问题， 见 #613 
- mip 的 vue 组件的 slot  用法
**5、自测机型和浏览器**
> 【免测】bugfix: 修复 slot 在 v-for 中失效问题

- packages/mip/src/viewer.js
#643 
mip cdn链接里的 a 标签 data-type=mip 可以通过mip-shell的方式跳转
所有 a 标签 data-type=mip  的 mip cdn 链接  
https://www-xmkanshu-com.mipcdn.com/c/www.xmkanshu.com/book/mip/read?bkid=685640121&crid=916&fr=bdgfh&mip=1&pg=4
代理测试，点击下一页，url一直都是这种 mip cdn 的链接
**5、自测机型和浏览器**
> mip cdn链接可以通过mip-shell跳转

- packages/mip/src/polyfill.js
#638 
去掉 QQ 浏览器下对 `fetch` 的处理
低版本 QQ 浏览器下，对 fetch 支持不好的浏览器下，xhr 请求没带 cookie
**5、自测机型和浏览器**
> [免测]去掉 QQ 浏览器下的特殊处理

- packages/mip/src/styles/mip-base.less
#664 
bugfix
iOS 下的页面滚动
**5、自测机型和浏览器**
> 【免测】修复 iOS 手百下页面无法滚动的问题

- packages/mip/src/components/mip-img.js
#651 
之前的改动是为了保持和 picture 实际加载图片一致，popup 会过滤没有加载完成的图片
现在改为 popup 应包括未加载的图片，没有必要只显示已加载图片
mip-img popup 功能
**5、自测机型和浏览器**
>  移除 mip-img popup 对 loaded 的筛选

- packages/mip/examples/mip2/scrollToHash-test.html
- packages/mip/src/components/mip-img.js
- packages/mip/src/page/index.js
- packages/mip/test/specs/components/mip-img.spec.js
- packages/mip/test/specs/page/page.spec.js
#673 
使用对 scrollTo 封装的 handleScrollTo，该方法通过 util.rect.getElementRect 获取元素到页面顶部的距离，而不是使用 offsetTop，能够正确滚动到元素所在位置。
使用 scrollToHash 方法进行滚动的锚点。
**5、自测机型和浏览器**
> 修复 scrollToHash 当锚点的祖先存在定位元素时不能滚动到锚点的问题

- packages/mip-cli/CHANGELOG.md
- packages/mip-cli/package-lock.json
- packages/mip-cli/package.json
less 升级至 3.10.0 导致和 less-loader 同时使用时编译出错，见：
https://github.com/less/less.js/issues/3414
先锁定版本，不影响正常编译。
**5、自测机型和浏览器**
> update cli to 1.5.15

- docs/docs/interactive-mip/event-and-action.md
- docs/docs/interactive-mip/expression.md
- docs/docs/interactive-mip/introduction.md
- packages/mip/src/util/event-action/grammar/basic.js
- packages/mip/src/util/event-action/grammar/event-argument.js
- packages/mip/src/util/event-action/whitelist/basic.js
- packages/mip/test/specs/util/parser/basic.spec.js
- packages/mip/test/specs/util/parser/event-argument.spec.js
- packages/mip/test/specs/util/parser/parse.spec.js
#679 
1. MIP.scrollTo/ MIP.navigateTo 等方法参数支持 Plain Object 的形式，并修改文档优先推荐这种写法，即从 `MIP.navigateTo(url='xxx', target='_blank')` 的写法优先推荐采用 `MIP.navigateTo({ url: 'xxx', target: '_blank' })`；
2. 新增 String.prototype.trim；
3. 新增 Plain Object 计算属性 `{[1 + '2']: 3}`；
新增逻辑，对线上无影响
**5、自测机型和浏览器**
> 统一 MIP 表达式的语法形式

- packages/mip-cli/package-lock.json
- packages/mip-cli/package.json
- packages/mip-component-validator/package-lock.json
- packages/mip-component-validator/package.json
- packages/mip-component-validator/src/rules/component-npm-whitelist.js
- packages/mip-component-validator/src/rules/lib/whitelist.txt
- packages/mip-sandbox/lib/keywords-generate.js
- packages/mip-sandbox/package-lock.json
- packages/mip-sandbox/package.json
- packages/mip/package-lock.json
- packages/mip/package.json
#725 
- 增加白名单 swanInvoke
- 迁移 mip-component-validator 的 whitelist.txt bos 地址
无
- mip-cli 可正常使用
**5、自测机型和浏览器**
> 增加 swanInvoke 白名单

- packages/mip/src/components/mip-video.js
#729 
1. 针对 android 手百环境，将 t7-video-player-type 从 inline 改成 h5
1. video 在安卓手百环境下打开的情况
1. android 普通浏览器页面测试 examples/builtin-components/mip-video.html 各个 case 正常
2. android 手百浏览上述页面，已修复锁屏后打开自动播放问题
3. ios 普通浏览器测试上述页面正常
4. ios 手百浏览上述测试页面正常
**5、自测机型和浏览器**
> 仅针对安卓手百将播放器的播放模式切换回 h5

- packages/mip/src/components/mip-video.js
[mip-video 在安卓qq浏览器脱离文档流](https://github.com/mipengine/mip2/issues/733)
video属性添加针对浏览器的如下配置:
'playsinline',
'x5-playsinline',
'webkit-playsinline',
't7-video-player-type',
'x5-video-player-type',
'x-webkit-airplay'
不会影响
android QQ浏览器添加x5-video-player-type属性，让视频没有脱离文档流
**5、自测机型和浏览器**
> 开放video的针对浏览器的属性的自定义#733

- packages/mip/src/styles/mip-shell.less
#731 
1. 增加 mip-shell-header-logo 的样式，防止被 min-width/min-height/max-width/max-height 的站点自定义样式污染；
1. 医疗 MIP 页；
1. 普通 MIP 页不受影响；
2. 目前正常显示的医疗 MIP 页也不受影响；
3. logo 被拉伸的医疗 MIP 页 logo 显示正常；
**5、自测机型和浏览器**
> 【BUGFIX】消除自定义样式 min-width/min-height 对 MIP 固定顶部栏样式所造成的影响
