mipengine/mip2

packages/mip/examples/page/iframe/iframe.html
packages/mip/src/components/mip-shell/index.js
packages/mip/src/index.js
packages/mip/src/mip1-polyfill/element.js
packages/mip/src/page/index.js
packages/mip/src/page/util/dom.js
packages/mip/src/page/util/ease-scroll.js
packages/mip/src/register-element.js
packages/mip/src/resources.js
packages/mip/src/styles/mip-base.less
packages/mip/src/styles/mip-page.less
packages/mip/src/util/dom/rect.js
packages/mip/src/viewer.js
packages/mip/src/viewport.js

fix: scroll in ios-iframe

---

docs/components/builtin/mip-carousel.md
packages/mip/src/components/mip-carousel.js

mip-carousel 对外暴露切换完成时的事件，供开发者处理一些自定义需求；

mip-carousel 新增切换完成的事件

---

docs/util/util-fn.md

add util fn doc

---

docs/extensions/builtin/mip-video.md
packages/mip/src/components/mip-video.js

Mip video styleguide

---

packages/mip/src/components/mip-shell/index.js

提pr时需要关联issue，请大家注意哦~~~
修复 #107 
BUG的情况需要同时满足：
1. 安卓机器
2. SF情况下
3. 目标页面包含异步修改高度的情况（例如发送AJAX，在响应中渲染页面）
符合上述2个条件的页面。目前已知的有：
1. 保险详情页面
2. 菩提树列表页面
3. 蓝犀牛订单页面（订单超过一屏幕时）
4. 法务详情页面
**3、自测 checklist**
上述页面均由我和 @zhuguoxi  自测过
**4、需要覆盖的场景和case**
**5、自测机型和浏览器**

修复安卓浏览器下切页面滚动的问题

---

.travis.yml

fix: add dev branch build

---

packages/mip/src/components/mip-shell/index.js

#132 
允许在读取后续页面配置时处理这个匹配的配置
新增功能，不影响线上
已和 @Espoir-L 通过 BOS 测试无误
**5、自测机型和浏览器**

增加processShellConfigInLeaf方法

---

packages/mip/examples/page/tree.html
packages/mip/src/components/mip-shell/index.js
packages/mip/src/viewer.js

#114 #132 
允许在读取后续页面配置时处理这个匹配的配置
允许开发者通过 API 的方式从已缓存页面中直接调出并切换
新增功能，不影响线上
已和 @Espoir-L @ShawnTu 分别通过 BOS 测试无误
**5、自测机型和浏览器**

ISSUE 114 & 132 紧急上线

---

packages/mip/src/resources.js
packages/mip/src/util/platform.js
packages/mip/test/specs/util/platform.spec.js

#123 
1、MIP.util.platform增加对支付宝的识别
2、修复iOS8不支持Number.isFinite
新增功能，不会影响其他
**5、自测机型和浏览器**
**6、自测方式
自己写了个页面进行测试，不在代码库里。
在支付宝中打开会弹出true，其他返回false。

Feature platform alipay && isFinite

---

docs/codelabs/mip-started/project.md

Master doc 修改了文档一个链接

---

packages/mip/examples/page/index.html
packages/mip/src/components/mip-shell/index.js
packages/mip/src/util/dom/rect.js

#150 
让 a 链接上的 `data-title` 重新生效
线上暂无使用 `data-title` 的链接
在examples中添加了带有 `data-title` 的 a 链接，测试效果正常
**5、自测机型和浏览器**

Dev 150 title

---

docs/guide/basic/newbie.md

doc 错误链接修改

---

packages/mip/src/vue-custom-element/utils/props.js
packages/mip/test/specs/vue-custom-element/utils/props.spec.js

#170
- 修复多层 mixin 无效的 bug
无
Chrome 模拟器
```js
let mixins2 = {
props: {
attr: Boolean
}
}
let mixins1 = {
mixins: [mixins2]
}
let props = getProps({
mixins: [mixins1]
})
expect(props).to.deep.equal({
camelCase: ['attr'],
hyphenate: ['attr'],
types: {
attr: Boolean
}
})
```
**5、自测机型和浏览器**
无兼容性问题

🐛 fix mixin props

---

packages/mip/src/components/mip-bind/bind.js
packages/mip/src/components/mip-bind/compile.js
packages/mip/src/components/mip-bind/observer.js
packages/mip/test/specs/components/mip-bind.spec.js

#175 
修复了因类型判断问题导致当设置数据为 null时会报错的bug
以及修改了两处单词拼写错误
设置数据的功能
已跑单测
**5、自测机型和浏览器**

fix typo & fix null compile error

---

packages/mip-cli/lib/generate.js

**相关 ISSUE:**  [https://github.com/mipengine/mip2/issues/190](https://github.com/mipengine/mip2/issues/190)
mip2 cli 使用 add 命令新增组件时，支持在  README.md 自动写入脚本地址
mip2 cli 新增功能，对 MIP 核心**无影响**。

Dev readme url

---

packages/mip/src/viewer.js

修复IOS输入框聚焦位置不对的问题
修复IOS输入框聚焦位置不对的问题
菩提树的一个表单页面
@zhuguoxi 使用代理测试效果正常
**5、自测机型和浏览器**

去掉scrollIntoView

---

packages/mip-cli/README.md
packages/mip-cli/package.json

修改 package.json cli 版本至 1.2.3

---

packages/mip/src/components/mip-video.js

#160 
兼容qq浏览器
新增功能
**5、自测机型和浏览器**

兼容qq浏览器，uc暂时放弃

---

packages/mip-cli/README.md
packages/mip-cli/package-lock.json
packages/mip-cli/package.json
packages/mip-component-validator/package-lock.json
packages/mip-component-validator/package.json

无
1. 升级 mip-component-validator 版本号
2. 升级发布 mip-cli 版本号
mip-cli 校验相关
无

升级mip-component-validator版本

---

packages/mip/src/components/index.js

[免测]注册mip-rem

---

docs/extensions/builtin/meta.json
docs/extensions/builtin/mip-rem.md
docs/extensions/builtin/mip-video.md

【免测】修改文档，补充mip-rem和video的说明

---

packages/mip/src/components/mip-video.js
packages/mip/src/styles/mip-video.less
packages/mip/test/specs/components/mip-video.spec.js

#172 
增加不播放视频的页面
新功能
**5、自测机型和浏览器**

增加不播放视频的页面

---

packages/mip/src/components/mip-shell/index.js
packages/mip/src/viewer.js

#199 
修复 ios 某些机型滚动的问题
配合 SF 修复iframe高度的问题
主要在于切换页面，和打开输入法
已经由 QA @gaoshan003  测试过了
**5、自测机型和浏览器**

Dev 199 iframe

---

packages/mip/src/components/mip-rem.js
packages/mip/test/specs/components/mip-rem.spec.js

更新mip-rem组件的默认值
新增功能
还是以前的测试页面，mip-rem.html
**5、自测机型和浏览器**

更新mip-rem默认值

---

packages/mip/package.json
packages/mip/src/styles/mip-shell.less
packages/mip/src/viewer.js

#274 
修复安卓下点击输入框时弹起的软键盘遮挡输入框的的问题
线上有输入框（且位置偏下）的页面
已经和 @gaoshan003 通过分支测试过
**5、自测机型和浏览器**

安卓情况下自动对焦input

---

packages/mip/src/client-prerender.js
packages/mip/src/viewer.js

**1、升级点** 
修复在预渲染情况下，某些通信事件记录的时间点错误的问题。
影响 mip 性能统计指标 `msg`
已修复，性能日志符合预期。
**5、自测机型和浏览器**

fix: recoreded event time when prerender

---

packages/mip/src/util/json-parse.js
packages/mip/test/specs/util/json-parse.spec.js

#325 
修复bug
无
chrome 模拟器
**5、自测机型和浏览器**

🐛 修复 jsonparse 报错

---

packages/mip-cli/CHANGELOG.md
packages/mip-cli/package-lock.json
packages/mip-cli/package.json
packages/mip-component-validator/package-lock.json
packages/mip-component-validator/package.json
packages/mip-component-validator/src/rules/lib/whitelist.txt
packages/mip-sandbox/README.md
packages/mip-sandbox/lib/keywords.js
packages/mip-sandbox/package-lock.json
packages/mip-sandbox/package.json

#336 
#331 
- mip-sandbox 增加 DataView 白名单
- mip-cli 更新 mip-sandbox 版本依赖
1. 组件沙盒校验与组件沙盒处理会忽略 DataView
1. 普通沙盒校验正常使用
2. 忽略 DataView

【免测】mip-sandbox 增加 DataView 白名单

---

packages/mip/src/styles/mip-base.less

#182 
很早就通知修改了，应该没有影响。
**5、自测机型和浏览器**

删除 html 根元素 font-size:100px 的样式

---

packages/mip/src/styles/mip-base.less

恢复html font-size 100px

---

packages/mip/build/build.rollup.js
packages/mip/build/config.js

修改 dtm 加载性能指标的打点时间戳
提升 dtm 的统计时长
**5、自测机型和浏览器**

[免测]修改 dtm 加载性能指标的打点时间戳

---

packages/mip/src/components/mip-img.js

fix 修改导致无法显示图片的问题

---

packages/mip/src/resources.js

fix: 修复预渲染 prerender 属性失效

---

docs/guide/mip-cli/contribute-to-official-repo.md

#368 
upsteam => upstream
无
chrome、github
**5、自测机型和浏览器**

docs: 修改错误单词拼写

---

packages/mip/src/components/mip-shell/index.js
packages/mip/src/page/index.js

#321 
按照最新的方案，增加`page.prerender`函数中可复用iframe的判断标准（要求`window.MIP.version === '2'`），避免断网弱网时创建的iframe其实并没有渲染好的问题
线上没有使用这个功能
由小说QA晓雪负责测试和回归
**5、自测机型和浏览器**

MIP核心对小说无限下拉的支持

---

packages/mip/build/config.js

**1、升级点** 
将核心构建格式暂时切换到 umd
**5、自测机型和浏览器**

将核心构建格式暂时切换到 umd

---

packages/mip/src/components/mip-img.js
packages/mip/src/viewer.js
packages/mip/test/specs/components/mip-img.spec.js

2018-12-20 例行上线

---

packages/mip/src/components/mip-img.js

postMessage 导致跨域问题报错，影响了图片的错误处理逻辑，导致图片被隐藏
**5、自测机型和浏览器**

bugfix-cross-domain-error

---

packages/mip/src/components/mip-img.js
packages/mip/src/fixed-element.js
packages/mip/src/resources.js
packages/mip/src/styles/mip-base.less
packages/mip/src/styles/mip-img.less
packages/mip/test/specs/components/mip-img.spec.js

#440 #439 
修复 mip2 替换 mip1 的 bug 
- 图片显示
- mip-fixed
**5、自测机型和浏览器**

mip2 替换 mip1 的 bug 修复

---

packages/mip/src/fixed-element.js
packages/mip/src/page/util/dom.js

#442 
强制隐藏使用了position: fixed的自定义组件，而不是移除组件，同时输出warning，通知开发者修改
使用了position: fixed的组件，无功能性影响
**5、自测机型和浏览器**

【免测】pisition: fixed自定义组件报错优化

---

packages/mip/src/components/index.js
packages/mip/src/components/mip-fixed/index.js
packages/mip/src/components/mip-fixed/viewport-scroll.js
packages/mip/src/styles/mip-fixed.less
packages/mip/test/specs/components/mip-fixed.spec.js

#453 
完成mip-fixed迁移，添加过渡动画和关闭方法
mip-fixed组件
**5、自测机型和浏览器**

完成迁移mip1 mip-fixed

---

packages/mip/examples/mip1/index.html
packages/mip/src/util/index.js
packages/mip/src/util/log.js

无 ISSUE
增加了 log 模块
线上暂无使用，没影响
**5、自测机型和浏览器**

[免测]增加 log 模块

---

packages/mip/examples/builtin-components/mip-video.html
packages/mip/examples/mip1/index.html
packages/mip/src/components/index.js
packages/mip/src/components/mip-bind/bind.js
packages/mip/src/components/mip-fixed/index.js
packages/mip/src/components/mip-fixed/viewport-scroll.js
packages/mip/src/components/mip-video.js
packages/mip/src/styles/mip-fixed.less
packages/mip/src/util/index.js
packages/mip/src/util/log.js
packages/mip/src/viewer.js
packages/mip/test/specs/components/mip-fixed.spec.js
packages/mip/test/specs/components/mip-video.spec.js

1.15 核心例行上线

---

packages/mip/src/index.js
packages/mip/src/performance.js
packages/mip/src/services/extensions.js
packages/mip/src/util/dom/dom.js
packages/mip/src/util/dom/rect.js
packages/mip/test/specs/util/dom/dom.spec.js

#513 #514 
- 修复 async 引入模式下 document.body 为 null 的情况
- 修复 performance 在 async 引入模式下的 DOMContentLoaded 事件响应问题
由于调整了 viewport 执行时机，可能会影响一些整体 viewport 效果
**5、自测机型和浏览器**

修复 async 引入 mip 核心情况下的报错问题和性能打点问题

---

packages/mip/deps/mip-components-webpack-helpers.js

fix: 修复 async 导致样式插入错误的问题

---

packages/mip/src/base-element.js

fix: 修复 HTMLElement 构造函数

---

packages/mip/src/util/event-action.js
packages/mip/test/specs/util/event-action.spec.js

fix event reg

---

packages/mip-cli/CHANGELOG.md
packages/mip-cli/package-lock.json
packages/mip-cli/package.json

#534 
锁死 webpack-dev-middleware 版本
**5、自测机型和浏览器**

Hotfix cli middleware

---

packages/mip/src/base-element.js
packages/mip/src/services/vue-compat.js
packages/mip/src/util/index.js
packages/mip/test/karma.base.conf.js
packages/mip/test/specs/services/vue-compat.spec.js

**1、升级点** 
- 对于组件 JSON 数据中类似 `Infinity` 的情况额外处理
**2、影响范围** 
- 线上无任何影响
- 官网
**5、自测机型和浏览器**

【免测】fix: 新增组件 JSON 数据类型转换

---

packages/mip/src/viewer.js

**1、升级点** 
- 针对 target="_blank" 的 <a> 链接，使用默认行为
**2、影响范围**
**5、自测机型和浏览器**

fix: mip 链接使用默认行为

---

packages/mip/src/runtime.js
packages/mip/src/viewer.js

3.15 核心紧急上线

---

.lgtm.yml

增加 lgtm auto code review 机制
持续继承功能，对核心代码无影响
**5、自测机型和浏览器**

add lgtm config

---

packages/mip/src/index.js

fix: Register built-in components when document interactive

---

packages/mip/src/mip1-polyfill/index.js

**1、升级点** 
- 站长总喜欢在本地打开 html，现在不写协议的话会用 file 协议打开导致报错
**2、影响范围**
- 应该没影响
**5、自测机型和浏览器**

 fix: Fix external resources protocol

---

packages/mip/src/util/templates.js

**相关 ISSUE:** 
**1、升级点** 
- templates 允许编译自身为 \<template\> 的元素
**2、影响范围**
- 无
**5、自测机型和浏览器**

【免测】feat: 增强 templates 判断逻辑

---

packages/mip/src/services/extensions.js
packages/mip/src/styles/mip-border.less

fix: Fix base url calculation

---

packages/mip/src/components/mip-img.js
packages/mip/test/specs/components/mip-img.spec.js

mip-img 修复滑动调起

---

docs/components/builtin/mip-img.md

fix docs https

---

packages/mip/src/page/const/index.js
packages/mip/src/util/platform.js
packages/mip/src/viewer.js

#625 
新增 Baidu App NA 通信 android api
无
**5、自测机型和浏览器**

【免测】feat: 新增 NA android 端通信

---

docs/docs/getting-start/meta.json
docs/docs/getting-start/migrate-v1-to-v2.md
docs/docs/getting-start/newbie.md

新增 MIP 1.0 迁移到 2.0 的描述文档
文档改动，无影响
**5、自测机型和浏览器**

feat: 新增 MIP 1.0 迁移到 2.0 的描述文档

---

.travis.yml

fix build error of travis

---

packages/mip-cli/lib/builder/webpack/config/index.js
packages/mip-cli/lib/builder/webpack/config/ts-loader.js

add babel loader for ts
ts 组件的编译
**5、自测机型和浏览器**

fix：add babel loader for ts

---

packages/mip-cli/CHANGELOG.md
packages/mip-cli/package-lock.json
packages/mip-cli/package.json

增加 cli version
升级版本号，无功能代码
**5、自测机型和浏览器**

fix: 增加 cli version

---

packages/mip/src/client-prerender.js
packages/mip/src/runtime.js

为组件提供预渲染状态的判断方法。
提供新的 API，无影响线上功能
MIP 页面正常，预渲染状态获取正常
**5、自测机型和浏览器**

【免测】feat: 提供预渲染状态判断

---

packages/mip/src/polyfill.js

无
添加 fetch polyfill
**5、自测机型和浏览器**

[免测]添加 fetch polyfill

---

docs/contribute/development/meta.json

remove vue doc

---

packages/mip/examples/page/index.html
packages/mip/src/components/mip-shell/index.js
packages/mip/src/viewer.js

#648 
- 支持 hash 透传
- 支持 hash 传入自定义 logo 和 title 进行品牌露出
mip-shell 自带的 title 和 logo 逻辑
**5、自测机型和浏览器**

在百度 app 搜索结果页同步打开 mip 相关 feature 升级

---

packages/mip/src/styles/mip-page.less
packages/mip/src/viewer.js

#670 #667 
- 修复在 pc 快照页面的空白问题 #667 
- 修复 hash 追加拼接的问题 #670
- 新增 百度 app iOS 通信机制
- PC 快照页面  [快照示例](http://cache.baiducontent.com/c?m=9f65cb4a8c8507ed19fa950d100b92235c438014638c92422381c814c4735b361a26b6a6787952468083267001d8131ab5ae22376a4376b8c493ca5ddccbc5747ad37b63&p=c0759a43819f12a05aaed4275a&newp=8b2a971986cc47e41afcdc654553d8224216ed673cd7c44324b9d71fd325001c1b69e7be24271301d4c7776402af4c5de0f43478341766dada9fca458ae7c474&user=baidu&fm=sc&query=mipengine&qid=b59c09f40077f327&p1=2)
- hash 锚点跳转页面 https://www.mipengine.org/v2/docs/getting-start/start-writing-first-mip.html
**5、自测机型和浏览器**

修复 hash 锚点 bug

---

docs/docs/interactive-mip/event-and-action.md

#656 
增加关于升级新增的 event 和 action 文档说明
无
无
**5、自测机型和浏览器**

新增事件和行为的文档说明

---

docs/docs/assistant-development-tools/meta.json

mip2 site 文档过时而且存在一些格式、链接不可用等问题，隐藏该文档
**5、自测机型和浏览器**

hide mip2 site docs

---

docs/docs/meta.json

[文档修改] 加上全站 mip 的文档

---

docs/components/builtin/mip-carousel.md

[文档修改] 增加 carousel 的文档说明

---

docs/docs/interactive-mip/event-and-action.md

无
1. 同步新增 mip-action-macro 的文档说明
**5、自测机型和浏览器**

[文档更新] 同步更新 mip-action-macro 的文档说明

---

docs/api/global/mip-shell.md
docs/codelabs/all-sites-mip/sample-code.md
docs/components/builtin/mip-img.md
docs/components/builtin/mip-shell.md
docs/contribute/development/writing-mip-component-in-vue-style.md
docs/docs/all-sites-mip/mip-shell.md
docs/docs/assistant-development-tools/mip-sf.md
docs/docs/interactive-mip/data-driven.md
packages/mip/examples/mip2/mip-interact.html
packages/mip/test/specs/components/mip-carousel.spec.js
packages/mip/test/specs/components/mip-img.spec.js

#710 
1. 修改全部 http(s)://boscdn.baidu.com 的图片，替换成 https://gss0.baidu.com 的图片链接
部分文档和测试用例，不影响线上
单测全过
**5、自测机型和浏览器**

替换失效图片 url
